True flyweight
OpenFreeEnergy/gufe pull request #146
Opened 2023-03-01 21:25 UTC by dwhswenson

This ensures that only one `GufeTokenizable` exists in memory for any given gufe key.

Consider this more a proposal than a request to merge.

Significant changed behavior:

* `tokenizable.copy_with_replacements()` (with no args) used to give a distinct copy in memory. It no longer does this, since no two different objects in memory can have the same gufe key.
* several tests in `SmallMoleculeComponent` are now meaningless -- there were a bunch of tests predicated on the idea that two molecules were equal but not the same in memory. This is now testing tautologies (I had put a test in to ensure that those tests were not testing tautologies; that extra test is now failing).

The other test that is failing is due to #145.

This would also require changing the docs on [deduplication in memory](https://gufe.readthedocs.io/en/latest/guide/serialization.html#deduplication-in-memory).

2023-03-01 21:28 UTC, dwhswenson commented
@richardjgowers : Pull these changes into #141 and it should fix the tests (except the 2 that are failing here)

2023-03-02 00:02 UTC, mikemhenry commented on gufe/tokenization.py
> +        key = instance.key
You were not kidding when you said that it would take 2 lines of code to change this :rofl:

2023-03-02 05:35 UTC, dotsdl commented
I'm for this change. 

Originally we had reservations on going full [flyweight](https://python-patterns.guide/gang-of-four/flyweight/) for `GufeTokenizable` instantiation via `__init__`, since the expectation from some users may be that this always gets you a new object. The downside with this approach, as we've seen, is that duplicate objects are then allowed, and can lead to surprising consequences, with no clear benefit.

I think resolving this inconsistency is worth breaking any expectation that `__init__` gets a new, distinct object.

2023-03-02 05:39 UTC, dotsdl approved these changes
Looks great to me @dwhswenson; if we can fix the remaining failed tests, I'm for merging when satisfied.

2023-03-03 14:14 UTC, richardjgowers approved these changes

2023-03-05 17:19 UTC, richardjgowers requested changes
hmm, I'm not 1,000% confident that the rdkit tobinary will be as stable in output as we need, so I might reroll that

2023-03-09 18:55 UTC, richardjgowers approved these changes

2023-03-09 18:56 UTC, merged

2023-03-09 19:26 UTC, dwhswenson commented
> hmm, I'm not 1,000% confident that the rdkit tobinary will be as stable in output as we need, so I might reroll that

@richardjgowers : I take it you are now 1000% confident?

2023-03-09 22:10 UTC, richardjgowers commented
Yeah wrote something manual that was similar to what we had previously, but
also solves #145 as it is rdkit centric

On Thu, Mar 9, 2023 at 19:26, David W.H. Swenson ***@***.***>
wrote:

> hmm, I'm not 1,000% confident that the rdkit tobinary will be as stable in
> output as we need, so I might reroll that
>
> @richardjgowers <https://github.com/richardjgowers> : I take it you are
> now 1000% confident?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenFreeEnergy/gufe/pull/146#issuecomment-1462649110>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACGSGBYLV2FZMSQG2QJ4OO3W3IVH7ANCNFSM6AAAAAAVMSKUXU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>