adding mol name labels from ofe-name to mapping vis
OpenFreeEnergy/gufe pull request #241
Opened 2023-09-27 12:04 UTC by RiesBen

This pull request adds one nice small features to gufe mapping visualization:
- labeling mapped molecules with their `ofe-name`
![image](https://github.com/OpenFreeEnergy/gufe/assets/12428005/a37a7b18-7899-4ba9-bfa8-f41582677df1)

2023-09-27 12:12 UTC, pep8speaks commented
Hello @RiesBen! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`gufe/visualization/mapping_visualization.py`](https://github.com/OpenFreeEnergy/gufe/blob/3c001397443ff66ad7e385a84d312f7b1c9bef9b/gufe/visualization/mapping_visualization.py):

> [Line 151:80](https://github.com/OpenFreeEnergy/gufe/blob/3c001397443ff66ad7e385a84d312f7b1c9bef9b/gufe/visualization/mapping_visualization.py#L151): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)

2023-09-27 18:30 UTC, mikemhenry requested changes
Can you update the documentation to add a note that `ofe-name` is used to label the molecules? Also is this something that users might want to just turn off? Could the `ofe-name` be really ugly or is that completely in the users hands?

2023-10-02 07:51 UTC, richardjgowers commented
@mikemhenry I think there's also some magic where `Mol.GetProp('_Name')` (the semi canonical way of labelling a name in rdkit) is converted to `ofe-name` (and vice versa)

2023-11-22 16:14 UTC, richardjgowers approved these changes

2023-11-22 16:14 UTC, merged