Settings setting shortcut thing
OpenFreeEnergy/gufe pull request #255
Opened 2023-11-20 18:10 UTC by richardjgowers

fixes #254

Adds SettingsBaseModel.find_field and set_field to find and set a parameter name from anywhere within the nested Settings

2023-11-20 18:11 UTC, pep8speaks commented
Hello @richardjgowers! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`gufe/settings/models.py`](https://github.com/OpenFreeEnergy/gufe/blob/a95bf3f76ffd9ec49b6afb644097e851313c03bb/gufe/settings/models.py):

> [Line 66:80](https://github.com/OpenFreeEnergy/gufe/blob/a95bf3f76ffd9ec49b6afb644097e851313c03bb/gufe/settings/models.py#L66): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)

2023-12-12 18:43 UTC, mikemhenry approved these changes

2023-12-12 19:33 UTC, dwhswenson requested changes
I'm not keen on this because I'm concerned about synonyms. I can imagine a user thinking they're setting a temperature with `settings.temp`, but this actually sets a temp file name (especially if they're setting temperature with a string.)

2023-12-14 12:00 UTC, richardjgowers commented
```
In [5]: class Foo(BaseModel):
   ...:     temp: FloatQuantity['kelvin']
   ...:

In [6]: f = Foo(temp='10 K')

In [7]: f
Out[7]: Foo(temp=<Quantity(10.0, 'kelvin')>)

In [8]: f = Foo(temp='10')
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Cell In[8], line 1
----> 1 f = Foo(temp='10')

File ~/mambaforge/envs/openfe_env/lib/python3.10/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for Foo
temp
  Cannot convert from 'dimensionless' (dimensionless) to 'kelvin' ([temperature]) (type=type_error.dimensionality; units1=dimensionless; units2=kelvin; dim1=dimensionless; dim2=[temperature]; extra_msg=)
```

@dwhswenson I'm not sure we have to be worried about stray strings on Quantities.  It will only "work" if the string is also valid as a Quantity, so not paths, and simple ints/floats are "upcasted" into Quantities easily.  I think you're rightly worried about bad variable names here (temperature is much better than temp for example), but that's not really made much worse by this feature

2023-12-14 22:10 UTC, dwhswenson commented
@richardjgowers : You've got the mistake I'm concerned about backwards. I'm worried about stray "quantities" on strings (when given as string). If I thought `temp` controlled temperature, but it actually controlled a tempfile name, I could easily do this:

```python
In [1]: from pydantic import BaseModel

In [2]: class Foo(BaseModel):
   ...:     temp: str = "tempfile.dat"  # a filename
   ...:

In [3]: f = Foo(temp="10 K")

In [4]: f
Out[4]: Foo(temp='10 K')
```

That works just fine, and could lead to confusion and even incorrect science. Sure, it is user error, but we're giving them the gun and making it easier to point it at their foot.

2024-01-30 09:28 UTC, closed without merging