WIP: Add settings add chem comp
OpenFreeEnergy/gufe pull request #38
Opened 2022-07-25 16:23 UTC by RiesBen

Hi, here i try to add an initial draft of the chemComposition.
I also slightly modified the file structure, but this can be reverted if wished?

2022-07-25 16:23 UTC, pep8speaks commented
Hello @RiesBen! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`gufe/settings/models/__init__.py`](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/__init__.py):

> [Line 1:64](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/__init__.py#L1): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 2:34](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/__init__.py#L2): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 4:75](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/__init__.py#L4): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 5:80](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/__init__.py#L5): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (83 > 79 characters)
> [Line 5:84](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/__init__.py#L5): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 6:80](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/__init__.py#L6): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 7:80](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/__init__.py#L7): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)

* In the file [`gufe/settings/models/abstract.py`](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/abstract.py):

> [Line 3:1](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/abstract.py#L3): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`gufe/settings/models/chemical_composition.py`](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py):

> [Line 9:1](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L9): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 10:1](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L10): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 11:11](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L11): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 11:16](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L11): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 12:1](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L12): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 14:1](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L14): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 15:18](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L15): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 17:11](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L17): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 18:1](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L18): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 20:13](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L20): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 20:18](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L20): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 22:1](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L22): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 23:17](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L23): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 24:24](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L24): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 24:29](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L24): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 25:14](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L25): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 25:32](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L25): [E221](https://duckduckgo.com/?q=pep8%20E221) multiple spaces before operator
> [Line 27:1](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L27): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 28:1](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L28): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 29:26](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L29): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 29:30](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L29): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 30:13](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L30): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 30:17](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L30): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 31:14](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.py#L31): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 31:24](https://github.com/OpenFreeEnergy/gufe/blob/08262a3a3d9c4578dc61a1a1ea085b67353718c4/gufe/settings/models/chemical_composition.p [...]

2022-07-26 15:03 UTC, dotsdl reviewed
Thanks @RiesBen! I did a quick review on mostly style things. Can you tell me what these objects are supposed to do? It seems odd to me that we are including system composition as part of settings, but I don't know if I missed out on some discussions here.

2022-07-26 15:03 UTC, dotsdl commented on gufe/settings/models/chemical_composition.py
> +class Chemical_Entity(SettingsBaseModel):
No underscore in class name.

2022-07-26 15:03 UTC, dotsdl commented on gufe/settings/models/chemical_composition.py
> +class Protein_Cofactors(Chemical_Entity):
No underscore in class name.

2022-07-26 15:09 UTC, richardjgowers requested changes
I think this is off on a tangent a little.  `Settings` are designed to capture everything *except* this sort of information.  I think *all* of the information here will be collected in various `*Component` classes

2022-07-26 15:18 UTC, RiesBen commented
@richardjgowers @dotsdl 
Hm I see your point, I tried to add this layer as it was defined in the taxonomy doc. 
For a simulation setup I think, it might be beneficial to have a fast look up on this, to support the reduced potential settings or other layers. But I also see, that this is represented by the Component classes. 
Therefore one could also think about removing it again? Then we should also remove it from the doc, or did I miss understand the doc?

2022-07-26 15:31 UTC, IAlibay commented
> Then we should also remove it from the doc, or did I miss understand the doc?

My 2 cent is that I wouldn't remove them from the doc, the components are a "setting" in themselves, i.e. they define how the positions and chemistry of your system are "set".

2022-07-26 16:07 UTC, closed without merging