test openmm 8.2
OpenFreeEnergy/gufe pull request #406
Opened 2024-11-13 23:00 UTC by mikemhenry

confirm issue with pdb roundtrip is from openmm 8.2 (or some package version it pulls in/requires)

2025-03-21 23:34 UTC, mikemhenry commented
Okay now we are getting the pdb file issues, this is different than the hybrid topo stuff

2025-03-28 22:39 UTC, mikemhenry commented
This is what the coverage looks like:
![image](https://github.com/user-attachments/assets/6158991c-5675-4f46-b437-ea16cd4cacc3)
I will go back to skipping the coverage and just work on updating the files

2025-04-17 21:17 UTC, mikemhenry commented
Okay this is actually a bit of a mess. Now that I've updated our vendored files, we have a problem when using openmm 8.1.2, since we use openmm's objects here:
https://github.com/OpenFreeEnergy/gufe/blob/cd9b0f9cb53bd3c9fbde6dfe05019a25d1f0aa5a/gufe/components/proteincomponent.py#L416
but then our vendored objects here:
https://github.com/OpenFreeEnergy/gufe/blob/cd9b0f9cb53bd3c9fbde6dfe05019a25d1f0aa5a/gufe/components/proteincomponent.py#L500

So we get a `AttributeError: 'Atom' object has no attribute 'formalCharge'` error since we are using 8.1.2 to make the atom objects, but then our object (based on the openmm 8.2.0 code) to write out those objects, and since 8.2.0 is expecting the `Atom` attribute, we get an error.

A fix could be to use our vendored topology object instead (so we would use the vendored version of Topology instead of calling `self.to_openmm_topology()`)

2025-04-17 22:31 UTC, mikemhenry commented
I tried to use the vendored version of `Element` but b/c we check if it matches the openmm objects, we get this error:
```
    def assert_topology_equal(ref_top, top):
        assert ref_top.getNumAtoms() == top.getNumAtoms()
        for ref_atom, atom in zip(ref_top.atoms(), top.atoms()):
            assert ref_atom.name == atom.name
>           assert ref_atom.element == atom.element
E           assert <Element carbon> == <Element carbon>
E            +  where <Element carbon> = <Atom 0 (CH3) of chain 0 residue 0 (ACE)>.element
E            +  and   <Element carbon> = <Atom 0 (CH3) of chain 0 residue 0 (ACE)>.element
```

I don't want to modify the tests to fix this, so we can use openmm's version of the Element object. 

I did manage to use our vendored version of the bond objects.

2025-04-18 14:05 UTC, IAlibay approved these changes
This looks good to me, I do agree with the historical issues you've already raised @mikemhenry.. this vendor is quite messy.

My only requested change is in in terms of testing. As per yesterday's call, I'm of the opinion that it doesn't make sense to try to have tests pass against multiple openmm versions. Since it's mostly a PDB formatting things, matching 8.2 is "more correct" than matching pre-8.2. So my suggestion would be to only test PDB writing when testing with 8.2+.

2025-04-18 14:05 UTC, IAlibay commented on gufe/vendor/pdb_file/pdbfile.py
> +from openmm import Platform
It bafflles me as to why we vendor from OpenMM and then also import from it in the vendor 🤦🏽 (this is a complaint against the concept of this file, not this PR).

Again, something we're better off dealing with later.

2025-04-18 14:05 UTC, IAlibay commented on .github/workflows/ci.yaml
> +          - "8.1.2"
Can we skip PDB checking tests for pre-8.2? That way CI won't fail.

2025-04-18 14:06 UTC, IAlibay requested changes
Oops technically that was a "requested changes".

2025-04-21 20:34 UTC, IAlibay commented
It would be good to try to get this into a release of gufe so we can more easily do an openmm 8.2 rc release of OpenFE.

How feasible would it be to finish this PR in the next few days @mikemhenry ?

2025-04-22 14:29 UTC, mikemhenry commented on gufe/tests/conftest.py
> +    name: (lambda name=name: get_test_filename(name))
this was fun https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result

2025-04-22 15:49 UTC, mikemhenry commented
I will need to make another PR that vendors in openff-models since that will prevent us from being numpy 2 compatible

2025-04-22 16:31 UTC, mikemhenry commented
@IAlibay @dotsdl @atravitz We decided to just match openmm for now, and maybe raise an issue about it in openmm

2025-04-24 19:21 UTC, IAlibay commented on gufe/tests/conftest.py
>      name: URLFileLike(url=_pl_benchmark_url_pattern.format(name=name)) for name in _benchmark_pdb_names
Need to hard-code release version here (or better, just vendor all the PDBs into gufe)

2025-05-01 15:21 UTC, atravitz commented
addressed by https://github.com/OpenFreeEnergy/gufe/pull/539, closing.

2025-05-01 15:21 UTC, closed without merging